version: '3.8'

services:
  public-pool:
    container_name: public-pool
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "192.168.11.151:${STRATUM_PORT}:${STRATUM_PORT}/tcp"
      - "192.168.11.151:${API_PORT}:${API_PORT}/tcp"
      - "127.0.0.1:${STRATUM_PORT}:${STRATUM_PORT}/tcp"
      - "127.0.0.1:${API_PORT}:${API_PORT}/tcp"
      - "3333"
      - "3334"
    volumes:
      - "./${NETWORK}-DB:/public-pool/DB"
      - "./.env:/public-pool/.env:ro"
    environment:
      - NODE_ENV=production
      - RETRY_DELAY=5000
      - MAX_RETRIES=5
      - UV_THREADPOOL_SIZE=64
      - REQUEST_TIMEOUT=10000

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

